dist: trusty
branches:
  except:
  - /^dependabot\/.*$/

cache:
  pip: true
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

    # Percy secrets are included here to enable Percy's GitHub integration
    # on community-submitted PRs
    - PERCY_PROJECT=skylines/skylines
    - PERCY_TOKEN=81bf0245987c87eb4924eae0b085cb60596f2f0f4d4ffe27e171828535aa6812

jobs:
  fast_finish: true

  include:
    - &backend-test
      stage: test
      env: NAME=backend      # used only to make Travis UI show description

      language: python
      python: 2.7

      addons:
        postgresql: "9.5"
        apt:
          packages:
            - postgresql-9.5-postgis-2.3
            - python3.5-dev

      services:
        - postgresql
        - redis

      before_install:
        - pip install pipenv==2018.7.1

      install:
        - pipenv install --dev

      before_script:
        # Create the testing database
        - psql -U postgres -c 'CREATE DATABASE skylines_test;'

        # Install PostGIS extension into the database
        - psql -U postgres -d skylines_test -c 'CREATE EXTENSION postgis;'

        # Install fuzzystrmatch extension into the database
        - psql -U postgres -d skylines_test -c 'CREATE EXTENSION fuzzystrmatch;'

      script:
        # Run the test suite
        - pipenv run py.test -vv --color=yes --cov=skylines --cov-report term-missing:skip-covered

    - <<: *backend-test
      python: 3.5

    - stage: test
      env: NAME=black         # used only to make Travis UI show description

      language: python
      python: 3.6

      install:
        - pip install black==18.9b0

      script:
        - black config migrations skylines tests uwsgi *.py --check

    - stage: test
      env: NAME=frontend      # used only to make Travis UI show description

      language: node_js
      node_js: 10

      addons:
        chrome: stable

      before_install:
        - cd ember

        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add bower

      install:
        - yarn install
        - bower install

      script:
        - yarn lint
        - yarn test
