language: python

python:
  - 2.7

sudo: false

services:
  - postgresql
  - redis

cache:
  pip: true
  yarn: true

before_install:
  - nvm install 6
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower phantomjs-prebuilt

install:
  # Install SkyLines Python dependencies
  - pip install -e .

  # Install testing dependencies
  - pip install -r requirements.txt

  - cd ember
  - yarn install
  - bower install
  - cd ..

before_script:
  # Create the testing database
  - psql -U postgres -c 'CREATE DATABASE skylines_test;'

  # Install PostGIS extension into the database
  - psql -U postgres -d skylines_test -c 'CREATE EXTENSION postgis;'

  # Install fuzzystrmatch extension into the database
  - psql -U postgres -d skylines_test -c 'CREATE EXTENSION fuzzystrmatch;'

  - cd ember
  - node_modules/.bin/ember build
  - cd ..

script:
  # Run the test suite
  - py.test -vv --cov=skylines --cov-report term-missing:skip-covered

  - cd ember
  - yarn test
